name: CD - Deploy to Azure Container Instance

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login using OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Fetch ACR credentials
        run: |
          echo "Fetching ACR credentials from Azure"

          ACR_NAME="${{ vars.ACR_NAME }}"

          ACR_USERNAME=$(az acr credential show \
            --name "$ACR_NAME" \
            --query "username" -o tsv)

          ACR_PASSWORD=$(az acr credential show \
            --name "$ACR_NAME" \
            --query "passwords[0].value" -o tsv)

          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

      - name: Deploy container to Azure Container Instance
        run: |
          az container create \
            --resource-group rg-container-lab \
            --name dast-container \
            --image ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_NAME }}:latest \
            --cpu 1 \
            --memory 1.5 \
            --registry-login-server ${{ vars.ACR_LOGIN_SERVER }} \
            --registry-username $ACR_USERNAME \
            --registry-password $ACR_PASSWORD \
            --ip-address Public \
            --ports 80 \
            --restart-policy Always
