name: CD - Deploy to Azure Container Instance

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # -----------------------------
    # LOGIN
    # -----------------------------
    - name: Azure Login using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ vars.AZURE_CLIENT_ID }}
        tenant-id: ${{ vars.AZURE_TENANT_ID }}
        subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    # -----------------------------
    # STAGE 1: ENSURE ACI EXISTS
    # -----------------------------
    - name: Stage 1 - Ensure ACI exists with Managed Identity
      run: |
        if az container show \
          --resource-group rg-container-lab \
          --name dast-container \
          --only-show-errors >/dev/null 2>&1; then
          echo "ACI already exists"
        else
          echo "Creating ACI..."
          az container create \
            --resource-group rg-container-lab \
            --name dast-container \
            --location centralindia \
            --image mcr.microsoft.com/oss/nginx/nginx:1.25 \
            --os-type Linux \
            --assign-identity \
            --cpu 1 \
            --memory 1.5 \
            --restart-policy Never \
            --only-show-errors
        fi

    # -----------------------------
    # STAGE 2: GRANT ACR PULL
    # -----------------------------
    - name: Stage 2 - Grant AcrPull to ACI Identity
      run: |
        ACI_PRINCIPAL_ID=$(az container show \
          --resource-group rg-container-lab \
          --name dast-container \
          --query identity.principalId \
          -o tsv)

        echo "ACI Principal ID: $ACI_PRINCIPAL_ID"

        az role assignment create \
          --assignee $ACI_PRINCIPAL_ID \
          --role AcrPull \
          --scope /subscriptions/${{ vars.AZURE_SUBSCRIPTION_ID }}/resourceGroups/rg-security-lab/providers/Microsoft.ContainerRegistry/registries/${{ vars.ACR_NAME }} \
          --only-show-errors || true

    # -----------------------------
    # STAGE 3: DEPLOY REAL IMAGE
    # -----------------------------
    - name: Stage 3 - Deploy Application Image
      run: |
        az container update \
          --resource-group rg-container-lab \
          --name dast-container \
          --image ${{ vars.ACR_LOGIN_SERVER }}/${{ vars.IMAGE_NAME }}:latest \
          --ip-address Public \
          --ports 80 \
          --only-show-errors
